version: '3'
services:
  spark:
    # image: jupyter/pyspark-notebook:spark-3.5.0
    build: .
    container_name: spark-notebook
    ports:
      - 8888:8888 # this port for Jypyter notebook
      - 2718:2718
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - PYTHONPATH=${PYTHONPATH}:/home/jovyan
    volumes:
    - ../../src:/home/jovyan
    - ../../project:/home/jovyan/project
    - ../../assets/jars:/home/jovyan/jars
    - ../../warehouse:/warehouse
    - ../../requirements.txt:/home/jovyan/requirements.txt
    - ../../geeksdata:/home/jovyan/geeksdata
    - ../../:/home/jovyan
    working_dir:
      /home/jovyan
    networks:
      - standalone_net
    # This is the CMD to disable the token when you access the local jupyter lab. If you want to enable the
    # jupyter token again, let delete this block
    command: ["jupyter", "notebook", "--no-browser","--NotebookApp.token=''","--NotebookApp.password=''"]

networks:
  standalone_net:
    external: true
