version: '3'
services:
  spark:
    image: jupyter/pyspark-notebook
    container_name: spark-notebook
    ports:
      - 8888:8888
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - PYTHONPATH=${PYTHONPATH}:/home/jovyan
    volumes:
    - ../../src:/home/jovyan
    - ../../project:/home/jovyan/project
    - ../../assets/jars:/home/jovyan/jars
    - ../../data:/data
    - ../../requirements.txt:/home/jovyan/requirements.txt
    working_dir:
      /home/jovyan
    networks:
      - standalone_kafka_net

networks:
  standalone_kafka_net:
    external: true
